// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Search all UEX entity types (commodities, vehicles, items, locations)
 * from the local cache, falling back to direct API calls.
 * 
 * Parameters:
 * - `query`: free-text search string
 */
async apiSearch(query: string) : Promise<Result<ApiResponse<UexResult[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search UEX commodities only.
 */
async apiSearchCommodities(query: string) : Promise<Result<ApiResponse<UexResult[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search_commodities", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search UEX vehicles (ships + ground vehicles).
 */
async apiSearchVehicles(query: string) : Promise<Result<ApiResponse<UexResult[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search_vehicles", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search UEX items.
 */
async apiSearchItems(query: string) : Promise<Result<ApiResponse<UexResult[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search_items", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search UEX locations (terminals / stations).
 */
async apiSearchLocations(query: string) : Promise<Result<ApiResponse<UexResult[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_search_locations", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch buy/sell prices for a commodity by its UEX ID.
 * Serves from per-commodity cache key (e.g. `commodity_prices:42`).
 */
async apiCommodityPrices(commodityId: string) : Promise<Result<ApiResponse<PriceEntry[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_commodity_prices", { commodityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch raw commodity prices by commodity ID.
 */
async apiRawCommodityPrices(commodityId: string) : Promise<Result<ApiResponse<PriceEntry[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_raw_commodity_prices", { commodityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch item prices by item ID.
 */
async apiItemPrices(itemId: string) : Promise<Result<ApiResponse<PriceEntry[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_item_prices", { itemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch vehicle purchase prices by vehicle ID.
 */
async apiVehiclePurchasePrices(vehicleId: string) : Promise<Result<ApiResponse<PriceEntry[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_vehicle_purchase_prices", { vehicleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch vehicle rental prices by vehicle ID.
 */
async apiVehicleRentalPrices(vehicleId: string) : Promise<Result<ApiResponse<PriceEntry[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_vehicle_rental_prices", { vehicleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch fuel prices by terminal ID.
 */
async apiFuelPrices(terminalId: string) : Promise<Result<ApiResponse<PriceEntry[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_fuel_prices", { terminalId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch detailed entity metadata by kind and id.
 * Caches results for 24 hours under `entity_info:{kind}:{id}`.
 */
async apiEntityInfo(kind: string, entityId: string) : Promise<Result<ApiResponse<EntityInfo>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_entity_info", { kind, entityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get status for all cached collections.
 */
async cacheStatus() : Promise<Result<CollectionStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cache_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh a single collection by name.
 */
async cacheRefresh(collection: string) : Promise<Result<CacheRefreshResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cache_refresh", { collection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh all prefetchable collections.
 */
async cacheRefreshAll() : Promise<Result<CacheRefreshResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cache_refresh_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh all prefetchable collections, but only those whose TTL has expired.
 * This is the same logic used on startup.
 */
async cacheRefreshExpired() : Promise<Result<CacheRefreshResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cache_refresh_expired") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uexSearch(query: string, apiKey: string) : Promise<Result<UexResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uex_search", { query, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uexSearchAll(query: string, apiKey: string) : Promise<Result<UexResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uex_search_all", { query, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uexPrices(commodity: string, apiKey: string) : Promise<Result<PriceEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uex_prices", { commodity, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(newSettings: Settings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { newSettings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideOverlayCmd() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_overlay_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showOverlayCmd() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_overlay_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDebugInfo() : Promise<Result<DebugInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_debug_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGameState() : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFavorites() : Promise<Result<Favorite[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_favorites") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addFavorite(id: string, name: string, kind: string, slug: string, uuid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_favorite", { id, name, kind, slug, uuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeFavorite(id: string, kind: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_favorite", { id, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isFavorite(id: string, kind: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_favorite", { id, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the authenticated user's fleet from UEX.
 * Requires both `uex_api_key` and `uex_secret_key` to be configured.
 */
async hangarGetFleet() : Promise<Result<ApiResponse<HangarVehicle[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hangar_get_fleet") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Uniform response wrapper returned by every API command.
 */
export type ApiResponse<T> = { ok: boolean; data: T | null; error: string | null; 
/**
 * Indicates the data was served from an expired cache entry.
 * Frontend can show a "refreshing..." indicator when this is true.
 */
stale: boolean; 
/**
 * Total number of matches before any limit was applied (None when not applicable).
 */
total: number | null }
/**
 * Response from cache refresh operations.
 */
export type CacheRefreshResult = { ok: boolean; collection: string; error: string | null }
/**
 * Known collection names used as cache keys.
 */
export type Collection = "commodities" | "commodity_prices" | "raw_commodity_prices" | "item_prices" | "vehicle_purchase_prices" | "vehicle_rental_prices" | "fuel_prices" | "vehicles" | "items" | "locations" | "fleet"
/**
 * Per-collection debug status (CollectionStatus extended with is_refreshing + expires_at).
 */
export type CollectionDebugInfo = { key: string; display_name: string; cached_at: string | null; expires_at: string | null; ttl_secs: number; is_expired: boolean; is_refreshing: boolean; entry_count: number }
/**
 * Per-collection status info for the cache management UI.
 */
export type CollectionStatus = { collection: Collection; display_name: string; cached_at: string | null; ttl_secs: number; is_expired: boolean; entry_count: number }
/**
 * Comprehensive runtime snapshot returned to the debug panel.
 */
export type DebugInfo = { sc_detected: boolean; sc_focused: boolean; sc_hwnd: number | null; sc_window_x: number; sc_window_y: number; sc_window_w: number; sc_window_h: number; hotkey: string; log_path: string | null; overlay_opacity: number; uex_api_key_set: boolean; esc_closes_overlay: boolean; reset_on_open: boolean; max_search_results: number; cache_ttls: Partial<{ [key in string]: number }>; log_watcher_active: boolean; hotkey_registered: boolean; refreshing_collections: string[]; cache_total_keys: number; cache_collections: CollectionDebugInfo[]; 
/**
 * ISO8601 timestamp of the last background check tick.
 */
last_bg_check_at: string | null; 
/**
 * Seconds until the next background check (30s interval).
 */
next_bg_check_in_secs: number; 
/**
 * How long ago the last background check ran (seconds).
 */
last_bg_check_ago_secs: number | null; last_user_action: LastUserAction | null; 
/**
 * Most recent fetch events, newest first.
 */
fetch_log: FetchEvent[] }
/**
 * Detailed entity metadata from UEX API, with type-specific optional fields.
 */
export type EntityInfo = { id: string; name: string; kind: string; slug: string; code: string | null; company_name: string | null; wiki: string | null; game_version: string | null; commodity_kind: string | null; weight_scu: number | null; avg_buy: number | null; avg_sell: number | null; is_illegal: boolean | null; is_buyable: boolean | null; is_sellable: boolean | null; is_mineral: boolean | null; is_raw: boolean | null; is_refined: boolean | null; is_harvestable: boolean | null; section: string | null; category: string | null; size: string | null; color: string | null; name_full: string | null; scu: number | null; crew: string | null; length: number | null; width: number | null; height: number | null; mass: number | null; pad_type: string | null; url_photo: string | null; url_store: string | null; roles: string[] }
export type Favorite = { id: string; name: string; kind: string; slug: string; uuid: string; added_at: string }
/**
 * A single backend fetch event (prefetch, timer refresh, or manual cache refresh).
 */
export type FetchEvent = { 
/**
 * RFC3339 timestamp when the fetch completed.
 */
timestamp: string; 
/**
 * Collection storage key, e.g. "commodity_prices".
 */
collection: string; 
/**
 * Human-readable API endpoint summary, e.g. "/commodities_prices (per-entity, 120 calls)".
 */
endpoint: string; 
/**
 * Number of rows/entries fetched.
 */
row_count: number; 
/**
 * Wall-clock duration of the fetch in milliseconds.
 */
duration_ms: number; 
/**
 * What triggered this fetch: "startup", "timer", or "manual".
 */
triggered_by: string; ok: boolean; error: string | null }
/**
 * Initial game connection state returned to the frontend on mount.
 */
export type GameState = { sc_detected: boolean }
/**
 * A vehicle in the user's hangar/fleet from UEX API.
 */
export type HangarVehicle = { id: string; id_vehicle: string; name: string; model_name: string; serial: string | null; description: string | null; organization_name: string | null; is_hidden: boolean; is_pledged: boolean; date_added: string; url_photo: string | null }
/**
 * Configurable in-app keybinds (F-keys and combos that don't go through the Rust hook)
 */
export type Keybinds = { 
/**
 * Key combo to toggle the Settings panel (default: "F12")
 */
toggle_settings: string; 
/**
 * Key combo to toggle the Debug panel (default: "F11")
 */
toggle_debug: string }
/**
 * The last price/entity lookup issued by the user (via a price command).
 */
export type LastUserAction = { timestamp: string; 
/**
 * Entity kind, e.g. "commodity", "vehicle".
 */
kind: string; entity_id: string; 
/**
 * Cache collection key, e.g. "commodity_prices".
 */
collection: string; 
/**
 * "fresh", "stale", or "missing".
 */
source: string; row_count: number }
/**
 * Per-panel layout widths persisted alongside other settings
 */
export type LayoutWidths = { 
/**
 * Width of the left column (Favorites + Debug) in pixels
 */
left_panel_px: number; 
/**
 * Width of the settings side panel in pixels
 */
settings_panel_px: number; 
/**
 * Width of the search column when detail panel is open, as a percentage (0–100)
 */
search_split_pct: number; 
/**
 * Width of the search panel when it is the only element (centered), as a percentage (0–100)
 */
search_solo_pct: number }
/**
 * A price entry from UEX API.
 * Unified across all price types — entity metadata identifies the source.
 */
export type PriceEntry = { entity_id: string; entity_name: string; price_type: string; location: string; terminal: string; terminal_id: string; buy_price: number; sell_price: number; rent_price: number; scu_available: number | null; date_updated: string; orbit?: string; system?: string; faction?: string; scu_last?: number; scu_users?: number; scu_avg?: number; scu_min?: number; scu_max?: number; price_last?: number; price_users?: number; price_avg?: number; price_min?: number; price_max?: number; inventory_status?: number; inventory_status_avg?: number; container_sizes?: string; is_buy_location?: boolean }
/**
 * Application settings persisted as JSON to `%APPDATA%\SoulOverlay\settings.json`
 */
export type Settings = { 
/**
 * Global hotkey string (e.g., "Alt+Shift+S")
 */
hotkey: string; 
/**
 * UEX Corp API key
 */
uex_api_key: string; 
/**
 * UEX Corp secret key (for user-specific endpoints like fleet)
 */
uex_secret_key: string; 
/**
 * Optional custom log file path (None = use default)
 */
log_path: string | null; 
/**
 * Overlay opacity (0.0 - 1.0)
 */
overlay_opacity: number; 
/**
 * Whether pressing Escape closes the overlay (default: true)
 */
esc_closes_overlay: boolean; 
/**
 * Whether opening the overlay resets to the search tab and focuses the search bar (default: true)
 */
reset_on_open: boolean; 
/**
 * Maximum number of search results returned by api_search (default: 50)
 */
max_search_results: number; 
/**
 * Per-collection cache TTL overrides in seconds, keyed by Collection::storage_key().
 * Missing entries fall back to Collection::ttl_secs().
 */
cache_ttls: Partial<{ [key in string]: number }>; 
/**
 * User-adjusted panel layout widths
 */
layout_widths: LayoutWidths; 
/**
 * Base font size in pixels (default: 14)
 */
font_size: number; 
/**
 * In-app panel keybinds (not the global Rust hook hotkey)
 */
keybinds: Keybinds }
/**
 * A search result from UEX API.
 */
export type UexResult = { id: string; name: string; kind: string; slug: string; 
/**
 * UUID (items only). Used to fetch item details from the UEX API.
 */
uuid?: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
